

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    wait-time-in-ms-when-sync-empty: 0


spring:
  application:
    name: Eureka-Server
server:
  port: 8761
